### ISSUE TITLE
Nuget dependencies release -- Lost support for .NETStandard 2.0

### ISSUE THREAD

**Issue by BeachyHeadCode** [adamfoneil/JsonSettings#11]
The nuget.org release from 1.1.0 allows for .NETStandard 2.0 https://www.nuget.org/packages/JsonSettings.Library/1.1.0#dependencies-body-tab

1.2.0 restricts this to net8.0-windows7.0 https://www.nuget.org/packages/JsonSettings.Library/1.2.0#dependencies-body-tab

Request is reuploading to .NETStandard 2.0.

**Comment by adamfoneil** [comment]
@BeachyHeadCode I don't have bandwidth for this. Feel free to rework the dependencies in the solution

**Comment by adamfoneil** [comment]
fixed by @CZEMacLeod with #12

**Comment by adamfoneil** [comment]
@BeachyHeadCode @CZEMacLeod I'm pleasantly surprised this package is in actual use! This is really out of the blue. It's been forever since I actively worked on this as you can tell. I recently had reason to dig into ASP.NET Core data protection features -- essentially a cross-platform version of DPAPI, apparently. I've also pivoted to System.Text.Json for all json needs
